### ISSUE TITLE
Error at startup ...

### ISSUE THREAD

**Issue by kazuki43zoo** [kazuki43zoo/api-stub#6]
``` text
2016-07-15 12:09:06.600 ERROR 11076 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.builder.BuilderException: Error invoking SqlProvider method (com.kazuki43zoo.domain.repository.ApiResponseRepository$SqlProvider.findAll).  Cause: java.lang.InstantiationException: com.kazuki43zoo.domain.repository.ApiResponseRepository$SqlProvider] with root cause

java.lang.NoSuchMethodException: com.kazuki43zoo.domain.repository.ApiResponseRepository$SqlProvider.<init>()
        at java.lang.Class.getConstructor0(Unknown Source) ~[na:1.8.0_77]
        at java.lang.Class.newInstance(Unknown Source) ~[na:1.8.0_77]
        at org.apache.ibatis.builder.annotation.ProviderSqlSource.createSqlSource(ProviderSqlSource.java:89) ~[mybatis-3.4.0.jar!/:3.4.0]
        at org.apache.ibatis.builder.annotation.ProviderSqlSource.getBoundSql(ProviderSqlSource.java:73) ~[mybatis-3.4.0.jar!/:3.4.0]
        at org.apache.ibatis.mapping.MappedStatement.getBoundSql(MappedStatement.java:292) ~[mybatis-3.4.0.jar!/:3.4.0]
        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:81) ~[mybatis-3.4.0.jar!/:3.4.0]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148) ~[mybatis-3.4.0.jar!/:3.4.0]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141) ~[mybatis-3.4.0.jar!/:3.4.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_77]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_77]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_77]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_77]
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:434) ~[mybatis-spring-1.3.0.jar!/:1.3.0]
        at com.sun.proxy.$Proxy52.selectList(Unknown Source) ~[na:na]
        at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:231) ~[mybatis-spring-1.3.0.jar!/:1.3.0]
        at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:128) ~[mybatis-3.4.0.jar!/:3.4.0]
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:68) ~[mybatis-3.4.0.jar!/:3.4.0]
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:53) ~[mybatis-3.4.0.jar!/:3.4.0]
        at com.sun.proxy.$Proxy61.findAll(Unknown Source) ~[na:na]
        at com.kazuki43zoo.domain.service.ApiResponseService.findAll(ApiResponseService.java:36) ~[api-stub-core-1.0.0-SNAPSHOT.jar!/:1.0.0-SNAPSHOT]
        at com.kazuki43zoo.domain.service.ApiResponseService$$FastClassBySpringCGLIB$$62a7f42e.invoke(<generated>) ~[api-stub-core-1.0.0-SNAPSHOT.jar!/:1.0.0-SNAPSHOT]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.2.7.RELEASE.jar!/:4.2.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720
...
```

**Comment by kazuki43zoo** [comment]
groovyだとinterfaceの内部クラスは明示的にstaticにしたいと認識されないようだ・・。
